-- wezterm.local.template.lua
-- ============================================================
-- LOCAL CONFIGURATION TEMPLATE
-- ============================================================
-- This file is a template for local machine-specific settings.
-- Instructions:
--   1. Copy this file to wezterm.local.lua (in the same directory)
--   2. Uncomment the shell configuration you prefer
--   3. Do NOT commit wezterm.local.lua (it's in .gitignore)
--
-- IMPORTANT: This file must return a Lua table.
--   Keys in the table override the corresponding config fields
--   in wezterm.lua. Do NOT use `config.xxx = ...` here.
-- ============================================================

-- ============ PowerShell (Windows native) ============
-- return {
-- 	default_prog = { "pwsh.exe", "-NoLogo" },
-- }

-- ============ WSL (Ubuntu via Windows Subsystem for Linux) ============
-- return {
-- 	default_domain = "WSL:Ubuntu",
-- 	default_prog = { "bash", "-l" },
-- }

-- ============ Additional Local Settings ============
-- Any config key can be overridden here. Examples:
-- return {
-- 	default_prog = { "pwsh.exe", "-NoLogo" },
-- 	font_size = 11,
-- 	color_scheme = "Dracula",
-- }
